Repository cockpit-project/bots, pull requests merged in 2019-12, with the labels that each got.

#240 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#294 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#298 testmap: Add new cockpit-composer rhel-8.2 branch
  task/testmap.py
Labels: no-test

#295 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#301 image-trigger: Drop selenium image refresh
  image-trigger
Labels: no-test

#297 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#302 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#303 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#304 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#306 Fixes for absent e2e cluster
  image-download
  image-refresh
  task/__init__.py
Labels: no-test

#308 testmap: Fix tests_for_image() to consider -distropkg contexts
  task/testmap.py
Labels: no-test

#310 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#311 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#309 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#316 tests-scan: Fix check for bots repo in scan_external_projects()
  tests-scan
Labels: no-test

#318 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#320 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#317 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#324 images: Drop selenium image
  images/scripts/selenium.bootstrap
  images/scripts/selenium.setup
  images/selenium
  task/testmap.py
Labels: no-test

#319 Fix tests explosions on tests-trigger
  tests-scan
Labels: no-test

#325 machine: Robustify cockpit (re)starting
  machine/machine_core/machine.py
Labels: no-test

#326 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#312 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#327 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#322 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#321 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#328 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#323 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#314 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#331 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#332 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#334 naughty: Close 60: Debian: parted clobbers in-memory state of extended partitions
  naughty/debian-stable/60-parted-clobbers-extended-partitions
  naughty/debian-testing/60-parted-clobbers-extended-partitions
  naughty/ubuntu-1804/60-parted-clobbers-extended-partitions
  naughty/ubuntu-stable/60-parted-clobbers-extended-partitions
Labels: bot

#340 testmap: test cockpit-composer master on rhel-8-2
  task/testmap.py
Labels: no-test

#341 testmap: Test c-podman on rhel-8-2 as well
  task/testmap.py
Labels: no-test

#344 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#345 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#346 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#347 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#350 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#351 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#348 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#352 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#354 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#358 naughty: Close 268: ABRT tests/reportd fails with: reportd task for workflow workflow_FedoraCCpp did not finish: Event collect_GConf has no handlers defined
  naughty/fedora-30/268-reportd-event-collect
  naughty/fedora-31/268-reportd-event-collect
Labels: bot

#355 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#356 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#353 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#360 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#362 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#366 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#364 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#369 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#367 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#368 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#371 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#370 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#361 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#363 po-refresh: Do not consider files with less than 50% coverage
  po-refresh
Labels: no-test

#378 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#379 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#377 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test
