Repository cockpit-project/bots, pull requests merged in 2019-10, with the labels that each got.

#72 Whitelist candlepin project for tests
  task/github.py
  task/test-github
Labels: no-test

#83 tests-policy: Pin down naughty repository
  tests-policy
Labels: no-test

#42 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#32 images: Shrink windows-10 image and install QRes
  images/scripts/windows-10.bootstrap
  images/windows-10
Labels: no-test

#84 make-checkout, tests-scan: Drop obsolete --base option
  make-checkout
  tests-scan
Labels: no-test

#90 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#91 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#85 Drop unneeded hack in fedora virt install
  images/scripts/virt-install-fedora
Labels: bot, no-test

#93 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#92 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#94 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#100 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#98 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#96 Image refresh for rhel-8-0
  images/rhel-8-0
Labels: bot, no-test

#99 Image refresh for fedora-29
  images/fedora-29
Labels: bot, no-test

#97 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#103 Stop preparing bots in make-checkout
  make-checkout
  tests-scan
Labels: no-test

#105 *-scan: Drop /dev/kvm check
  issue-scan
  tests-scan
Labels: no-test

#106 test: Drop deprecated imp module
  task/test-task
  test-bots
Labels: no-test

#107 .tasks: Fix path
  .tasks
Labels: no-test

#113 issue-scan: Drop --bots-ref
  issue-scan
Labels: no-test

#109 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#108 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#111 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#116 Some small cleanups in tests-invoke
  tests-invoke
Labels: no-test

#115 Always use log.html
  tests-invoke
  tests-scan
Labels: no-test

#119 naughty: Add pattern for Fedora 31 name_bind SELinux regression
  naughty/fedora-30/118-selinux-rpcbind-name_bind
  naughty/fedora-31/118-selinux-rpcbind-name_bind
Labels: no-test

#117 Cleanup in tests-invoke no.2
  tests-invoke
Labels: no-test

#120 test: Use 'git grep' for finding python files
  test/run
Labels: no-test

#121 Rebase in make-checkout and not in tests-invoke
  make-checkout
  tests-invoke
  tests-scan
Labels: no-test

#110 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#114 image-refresh: Move some test triggers to rhel-7.8
  image-refresh
  task/testmap.py
Labels: no-test

#124 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#123 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#129 Image refresh for fedora-29
  images/fedora-29
Labels: bot, no-test

#125 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#128 Image refresh for rhel-8-0
  images/rhel-8-0
Labels: bot, no-test

#95 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#131 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#132 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#127 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#141 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#143 Fix bogus trigger in image-refresh
  image-refresh
Labels: no-test

#140 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#144 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#147 naughty: Update to improved tests
  naughty/fedora-31/137-podman-stats-rootless
Labels: no-test

#148 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#152 Image refresh for rhel-8-0
  images/rhel-8-0
Labels: bot, no-test

#153 Image refresh for fedora-29
  images/fedora-29
Labels: bot, no-test

#154 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#156 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#155 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#150 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#159 testmap: Add experimental context for testing Firefox through CDP
  task/testmap.py
Labels: no-test

#162 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#165 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#163 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#167 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#171 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#168 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#179 Image refresh for fedora-29
  images/fedora-29
Labels: bot, no-test

#178 Image refresh for rhel-8-0
  images/rhel-8-0
Labels: bot, no-test

#173 naughty: Close 78: Selinux prevents setting timezone via timedatectl, prevents write to /etc/localtime
  naughty/fedora-31/78-selinux-timedatectl
  naughty/fedora-31/78-selinux-timedatectl-2
Labels: bot

#175 naughty: Close 76: podman Commit Container is extremely slow
  naughty/fedora-29/76-podman-commit-slow
  naughty/fedora-30/76-podman-commit-slow
Labels: bot

#176 naughty: Close 75: podman crashes on fedora-30 when doing bulk deletion of images and calling ListImages in parallel
  naughty/fedora-30/75-podman-image-deletion-listing-crash
  naughty/fedora-30/75-podman-image-deletion-listing-crash-2
Labels: bot

#174 naughty: Close 77: libvirtd sometimes crashes on rhel-8-1 when destroying guests
  naughty/rhel-8/77-libvirtd-crash-domain-destroy-test-failed
  naughty/rhel-8/77-libvirtd-crash-domain-destroy-test-finished
Labels: bot

#182 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#183 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#181 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#187 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#184 testmap: Declare rhel-8-2 test
  task/testmap.py
Labels: no-test

#188 naughty: Apply issue #80 to RHEL 8
  naughty/rhel-8/80-sssd-ssh-ticket-expired
Labels: no-test

#189 testmap: Run rhel-8-2 for cockpit master
  task/testmap.py
Labels: no-test

#190 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#192 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#191 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test
