Repository cockpit-project/bots, pull requests merged in 2019-11, with the labels that each got.

#193 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#194 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#199 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#197 Image refresh for fedora-29
  images/fedora-29
Labels: bot, no-test

#200 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#198 Image refresh for rhel-8-0
  images/rhel-8-0
Labels: bot, no-test

#207 images: Drop fedora-29
  image-trigger
  images/fedora-29
  images/scripts/fedora-29.bootstrap
  images/scripts/fedora-29.install
  images/scripts/fedora-29.setup
  machine/machine_core/machine_virtual.py
  naughty/fedora-29/65-pcp-pmfindprofile-crash
  naughty/fedora-29/65-pcp-pmfindprofile-crash-2
  naughty/fedora-29/65-pcp-pmfindprofile-crash-3
  naughty/fedora-29/65-pcp-pmfindprofile-crash-4
  naughty/fedora-29/66-nm-bond-autoconnect-slaves
  naughty/fedora-29/66-nm-bridge-autoconnect-slaves
  naughty/fedora-29/66-nm-team-autoconnect-slaves
  naughty/fedora-29/68-abrtd-crash-fn
  naughty/fedora-29/68-abrtd-crash-fn-2
  naughty/fedora-29/69-udisks2-fails-with-thin-snapshots
  naughty/fedora-29/69-udisks2-fails-with-thin-snapshots-2
  naughty/fedora-29/74-selinux-dac-override-firewalld
  naughty/fedora-29/9505-selinux-rpc-gsssd-getattr
  task/testmap.py
Labels: bot, no-test

#210 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#211 Drop ipa and candlepin images
  image-create
  images/candlepin
  images/ipa
  images/scripts/ipa.bootstrap
  images/scripts/ipa.setup
  task/testmap.py
Labels: no-test

#209 Change obsolete SSH ACCESS message
  machine/machine_core/machine.py
Labels: no-test

#219 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#158 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#223 Image refresh for fedora-atomic
  images/fedora-atomic
Labels: bot, no-test

#222 naughty: Close 79: Denied NetworkManager write to /var/tmp/dracut.*/systemd-cat while generating initrd image
  naughty/fedora-31/79-selinux-nm-system-cat
Labels: bot

#224 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#226 testmap: Stop testing cockpit master on RHEL 8.1
  task/testmap.py
Labels: no-test

#230 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#229 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#225 image-download: Add fallback RedHat-internal image server in AWS
  image-download
Labels: no-test

#231 testmap: Run Firefox verify tests on master branch
  task/testmap.py
Labels: no-test

#233 bots: Drop fedora-stock image
  images/fedora-stock
  images/scripts/fedora-stock.setup
Labels: no-test

#227 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#228 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#235 testmap: Enable fedora-coreos testing for Cockpit master
  task/testmap.py
Labels: no-test

#239 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#238 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#236 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#237 images: Drop fedora-atomic
  README.md
  image-create
  image-trigger
  images/fedora-atomic
  images/scripts/fedora-atomic.bootstrap
  images/scripts/fedora-atomic.install
  images/scripts/fedora-atomic.setup
  machine/machine_core/constants.py
  naughty/fedora-atomic/66-nm-bond-autoconnect-slaves
  naughty/fedora-atomic/66-nm-bridge-autoconnect-slaves
  naughty/fedora-atomic/66-nm-team-autoconnect-slaves
  task/testmap.py
  tests-policy
Labels: no-test

#245 images: Update cockpit/ws container on fedora-coreos with local packages/files
  images/scripts/fedora-coreos.install
Labels: no-test

#241 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#246 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#247 image-trigger: Drop non-existing ipa image
  image-trigger
Labels: no-test

#253 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#250 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#249 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#251 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#254 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#262 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#260 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#261 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#265 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#269 testmap: Add centos-8-stream to cockpit master tests
  task/testmap.py
Labels: no-test

#271 naughty: Close 137: Podman cannot load stats from rootless containers
  naughty/fedora-31/137-podman-stats-rootless
Labels: bot

#272 testmap: Add centos-8-stream to starter-kit master tests
  task/testmap.py
Labels: no-test

#273 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#267 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#275 task: Drop explicit python interpreter from sink invocation
  task/sink.py
Labels: no-test

#277 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#282 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#283 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#284 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#287 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#288 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#289 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#290 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test
