Repository cockpit-project/bots, pull requests merged in 2020-01, with the labels that each got.

#380 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#384 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#381 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#383 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#373 Image refresh for services
  images/services
Labels: bot, no-test

#387 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#349 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#365 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#388 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#376 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#386 Image refresh for F31
  images/fedora-31
Labels: bot, no-test

#382 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#393 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#391 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#394 vm-run: Fix networking for windows-10
  machine/machine_core/machine_virtual.py
  vm-run
Labels: no-test

#396 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#400 Migrate weldr/lorax rhel8-branch tests to rhel-8-2
  task/testmap.py
Labels: no-test

#402 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#395 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#405 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#401 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#397 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#398 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#404 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#411 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#399 testmap: only test cockpit-composer on fedora-31
  task/testmap.py
Labels: needswork, no-test

#407 naughty: Close 256: RHEL 8.2 regression: setting time fails: avc: denied { sys_time } for comm="timedatex"
  naughty/rhel-8/256-selinux-timedatex
Labels: bot

#408 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#392 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, needswork, no-test

#413 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#414 testmap: Drop cockpit rhel-8-appstream branch
  task/testmap.py
Labels: no-test

#416 images: Introduce rhel-8-2-distropkg
  images/scripts/rhel-8-2-distropkg.install
  task/testmap.py
Labels: no-test

#415 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#410 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#403 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#418 testmap: Drop leftover rhel-8-1 composer image refresh test
  task/testmap.py
Labels: no-test

#419 testmap: Declare rhel-8-2 subscription-manager test
  task/testmap.py
Labels: no-test

#417 testmap: Move cockpit master to rhel-8-2-distropkg
  task/testmap.py
Labels: no-test

#420 testmap: rhel-8-1retirements
  task/testmap.py
Labels: no-test

#421 po-{refresh,trigger}: Update issue title
  po-refresh
  po-trigger
Labels: no-test

#423 testmap: Move subscription-manager to rhel-8-2
  task/testmap.py
Labels: no-test

#429 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#424 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#425 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#427 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#428 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#432 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#426 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#434 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#436 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#435 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#431 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#422 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#433 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#441 tests-scan: Don't trigger external tests on bots PRs by default
  tests-scan
Labels: no-test

#450 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#454 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#456 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#455 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#451 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#458 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#459 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#463 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#462 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#461 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#473 Dear bots, F30 refresh, please?
  images/fedora-30
Labels: bot, no-test

#437 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#468 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#438 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#479 naughty: Close 80: krb5 regression: SSH GSS authentication fails with "Ticket expired"
  naughty/fedora-31/80-sssd-ssh-ticket-expired
  naughty/rhel-8/80-sssd-ssh-ticket-expired
Labels: bot
