Repository cockpit-project/bots, pull requests merged in 2020-09, with the labels that each got.

#1193 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1191 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1196 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1195 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1194 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1192 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1197 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#1199 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1200 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1201 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1202 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1204 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1203 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1205 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1207 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1208 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1211 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1210 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1209 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1212 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1214 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1215 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1217 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1218 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1219 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1224 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1220 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1227 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1226 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1222 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1228 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1229 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1230 images: Fix centos-8-stream image build
  images/centos-8-stream
  images/scripts/centos-8-stream.bootstrap
  images/scripts/centos-8-stream.install
  images/scripts/rhel.setup
  naughty/rhel-8/1235-selinux-plymouthd-sys_chroot
  naughty/rhel-8/1236-no-kvdo
Labels: bot

#1233 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1232 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1231 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1241 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1242 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1245 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1247 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1246 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1249 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1244 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1243 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1252 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, needswork, no-test

#1255 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1257 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1240 Image refresh for fedora-33
  images/fedora-33
Labels: blocked, bot, no-test

#1261 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1264 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1265 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1270 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test
