Repository cockpit-project/bots, pull requests merged in 2020-10, with the labels that each got.

#1272 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1267 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1274 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1275 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1276 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#1269 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1277 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1278 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#1283 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1286 naughty: Close 971: gnutls 3.6.14 broken in FIPS mode: FIPS140-2 self testing part 2 failed
  naughty/fedora-31/971-gnutls-fips
  naughty/fedora-31/971-gnutls-fips-firefox
  naughty/fedora-32/971-gnutls-fips
  naughty/fedora-33/971-gnutls-fips
Labels: bot

#1287 naughty: Close 932: udisks 2.9.0 regression: org.freedesktop.UDisks2.VolumeGroup.Delete does not clean up fstab mounts any more for deactivated LV
  naughty/debian-testing/932-udisks-deactivated-lv-cleanup
  naughty/rhel-8/932-udisks-deactivated-lv-cleanup
  naughty/ubuntu-stable/932-udisks-deactivated-lv-cleanup
Labels: bot

#1285 naughty: Close 1092: kexec_file_load failed: Accessing a corrupted shared library w/ 5.7.9-200.fc32.x86_64
  naughty/fedora-31/1092-kexec_file_load-corrupted
  naughty/fedora-32/1092-kexec_file_load-corrupted
  naughty/fedora-33/1092-kexec_file_load-corrupted
Labels: bot

#1289 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1290 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1271 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1288 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1282 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1280 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1281 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1279 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1295 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#1291 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1294 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1298 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1297 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1302 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1309 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1308 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1307 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1306 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1304 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1313 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1303 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1312 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1314 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1318 naughty: Close 1235: SELinux denial: avc: denied { sys_chroot } for comm="plymouthd"
  naughty/rhel-8/1235-selinux-plymouthd-sys_chroot
Labels: bot

#1316 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1321 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1328 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1323 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#1324 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1329 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1326 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, needswork, no-test

#1330 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1331 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1311 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: blocked, bot, no-test

#1327 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1213 testmap: move fedora 33 to master for cockpit-composer
  task/testmap.py
Labels: blocked

#1347 naughty: Close 1180: abrt-server errors when processing zstd compressed core dumps
  naughty/fedora-33/1180-abrt-processing-zstd
  naughty/fedora-33/1180-abrt-processing-zstd-1
  naughty/fedora-33/1180-abrt-processing-zstd-3
Labels: bot

#1348 naughty: Close 897: sssd 2.3.0 regression: Can't authenticate against AD any more
  naughty/fedora-32/897-sssd-ad-auth
  naughty/fedora-32/897-sssd-ad-auth-2
  naughty/fedora-33/897-sssd-ad-auth
  naughty/fedora-33/897-sssd-ad-auth-2
  naughty/rhel-8/897-sssd-ad-auth
  naughty/rhel-8/897-sssd-ad-auth-2
Labels: bot

#1349 naughty: Close 74: SELinux: avc: denied { dac_override } comm="firewalld"
  naughty/rhel-8/74-selinux-dac-override-firewalld
Labels: bot

#1342 images: Introduce rhel-8-4
  images/rhel-8-4
  images/scripts/rhel-8-4.bootstrap
  images/scripts/rhel-8-4.install
  images/scripts/rhel-8-4.setup
  images/scripts/rhel.setup
  naughty/rhel-8-4
  task/testmap.py
Labels: bot
