Repository cockpit-project/bots, pull requests merged in 2020-11, with the labels that each got.

#1361 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1360 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1359 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1355 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1362 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#1363 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1364 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1358 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1370 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1373 Add naughty for libvirt crash in debian stable
  naughty/debian-stable/1372-libvirt-crashes-on-test-teardown
Labels: no-test

#1378 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1377 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1382 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1381 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1379 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1383 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1387 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1389 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1385 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1384 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1396 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1398 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1400 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1401 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1405 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1404 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1397 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1399 Image refresh for debian-testing
  images/debian-testing
Labels: bot, needswork, no-test

#1409 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1408 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1403 Image refresh for fedora-33
  images/fedora-33
Labels: bot, needswork, no-test

#1413 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1414 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1411 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1421 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1420 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1416 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1417 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test
