Repository cockpit-project/bots, pull requests merged in 2020-04, with the labels that each got.

#704 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#703 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#706 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#707 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#705 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#636 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#702 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#701 Image refresh for fedora-31
  images/fedora-31
Labels: bot, no-test

#710 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#709 Image refresh for services
  images/services
Labels: bot, no-test

#712 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#700 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#720 naughty: Close 579: Virsh cannot attach iscsi disk device to domain
  naughty/fedora-32/579-virsh-device-attach
Labels: bot

#725 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#724 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#723 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#722 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#713 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#721 Image refresh for openshift
  images/files/openshift.kubeconfig
  images/openshift
Labels: bot, no-test

#728 Image refresh for ubuntu-1804
  images/ubuntu-1804
Labels: bot, no-test

#731 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#730 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#737 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#732 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#740 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#739 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#741 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#746 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#748 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#743 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#735 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#745 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#744 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#747 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#749 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#751 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#750 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#753 testmap: update cockpit-composer organization
  task/testmap.py
Labels: blocked

#754 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#760 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#761 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#765 naughty: Close 678: [RHEL 7.9] kdump does not generate any report
  naughty/rhel-7/678-kdump-no-report
Labels: bot

#766 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#767 Image refresh for fedora-30
  images/fedora-30
Labels: bot, no-test

#770 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#768 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#769 Image refresh for rhel-8-2
  images/rhel-8-2
Labels: bot, no-test

#785 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#783 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#792 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#791 Image refresh for rhel-7-7
  images/rhel-7-7
Labels: bot, no-test

#790 Image refresh for continuous-atomic
  images/continuous-atomic
Labels: bot, no-test

#789 Image refresh for rhel-8-1
  images/rhel-8-1
Labels: bot, no-test

#782 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#794 naughty: Close 583: rhel-8.2 cockpit crashes in ja/ko/zh locales due to broken translations
  naughty/rhel-8/583-rhel-8.2-broken-translations
Labels: bot

#788 Image refresh for rhel-7-8
  images/rhel-7-8
Labels: bot, no-test

#795 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#784 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#781 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#802 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#762 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, needswork, no-test

#804 Image refresh for fedora-31
  images/fedora-31
Labels: no-test

#808 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test
