Repository cockpit-project/bots, pull requests merged in 2021-12, with the labels that each got.

#2678 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2666 Image refresh for arch
  images/arch
Labels: needswork, bot, no-test

#2682 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#2684 naughty: Close 2483: qemu does not support SGA
  naughty/rhel-9/2483-qemu-sga-support
Labels: bot

#2691 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2689 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2685 naughty: Close 2386: rhel-9-0: udisksd sometimes crashes during shutdown
  naughty/rhel-9/2386-udisksd-crashes-during-shutdown
Labels: bot

#2692 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2694 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2693 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2699 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2698 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2697 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2696 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2695 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2702 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2700 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2714 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2713 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#2712 Image refresh for arch
  images/arch
Labels: bot, no-test

#2709 naughty: Close 1784: fedora-34: reportd crashes in reportd_task_start
  naughty/fedora-34/1784-reportd-crash-task_start
Labels: bot

#2715 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2716 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2705 constants, testmap: Set TEST_DEFAULT_OS to fedora-35
  lib/constants.py
  lib/testmap.py
Labels: blocked

#2720 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2721 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2725 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2723 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2722 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2727 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2728 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2724 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2726 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2735 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2736 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2737 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2740 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2739 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2738 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2742 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2745 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2743 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2748 naughty: Close 1785: fedora-34: reportd crashes
  naughty/fedora-34/1785-reportd-crash-g_bus_unown_name
Labels: bot

#2747 naughty: Close 2426: TestStorageMounting.testDuplicateMountPoints flake on ubuntu-2004: lvcreate is sometimes missing uevent
  naughty/ubuntu-2004/2426-lvcreate-uevent
Labels: bot

#2744 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot

#2751 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2752 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2756 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2755 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2758 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2760 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test
