Repository cockpit-project/bots, pull requests merged in 2021-08, with the labels that each got.

#2263 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2265 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2271 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2270 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2269 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2277 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2279 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2278 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2280 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2281 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2283 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2284 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2286 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2287 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2288 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2296 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2295 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2294 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2293 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2301 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2300 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2297 naughty: adjust podman test expected failure
  naughty/rhel-9/2158-podman-api-call-loses-data-2
Labels: no-test

#2298 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2299 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2305 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2308 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2309 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2307 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2315 naughty: Close 2218: targetcli create hangs forever
  naughty/fedora-35/2218-targetcli-hang
Labels: bot

#2322 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2321 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2320 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2325 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2324 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2328 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2327 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2332 naughty: Close 1862: rhel-9 kernel panic in FIPS mode
  naughty/rhel-9/1862-fips-kernel-oops
Labels: bot

#2326 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2331 naughty: Close 2230: systemd[1]: Assertion 'a <= b' failed at src/libsystemd/sd-event/sd-event.c:2903, function sleep_between(). Aborting
  naughty/fedora-34/2230-systemd-assert-sleep_between
  naughty/fedora-coreos/2230-systemd-assert-sleep_between
Labels: bot

#2333 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2329 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2355 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2354 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2358 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2357 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test
