Repository cockpit-project/bots, pull requests merged in 2021-09, with the labels that each got.

#2366 naughty: Close 2134: rhel-8-5: set fips=1,system boot fail
  naughty/rhel-8/2134-fips-enabled-boot
Labels: bot

#2369 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2376 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2374 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#2372 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2373 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2375 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2381 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2379 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2378 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2383 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2382 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2394 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2396 naughty: Close 2243: Boot in FIPS mode panics
  naughty/fedora-33/2243-fips-panic
  naughty/fedora-34/2243-fips-panic
Labels: bot

#2390 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2402 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2399 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2407 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2405 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2410 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2409 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2408 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2411 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2414 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2417 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2416 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2418 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2401 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2419 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2421 naughty: Close 2097: podman: Selinux is preventing non root user to build a container image
  naughty/fedora-33/2097-selinux-rootless-podman
  naughty/rhel-9/2097-selinux-rootless-podman
Labels: bot

#2424 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2423 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2422 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2425 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2430 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2429 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2431 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2433 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2444 naughty: Close 69: debian-stable: UDisks2 fails to create snapshots of thin volumes
  naughty/debian-stable/69-udisks2-fails-with-thin-snapshots
  naughty/debian-stable/69-udisks2-fails-with-thin-snapshots-2
  naughty/debian-testing/69-udisks2-fails-with-thin-snapshots
  naughty/debian-testing/69-udisks2-fails-with-thin-snapshots-2
  naughty/rhel-7/69-udisks2-fails-with-thin-snapshots
  naughty/rhel-7/69-udisks2-fails-with-thin-snapshots-2
  naughty/rhel-8/69-udisks2-fails-with-thin-snapshots
  naughty/rhel-8/69-udisks2-fails-with-thin-snapshots-2
Labels: bot

#2443 naughty: Close 838: Libvirtd dumps core on rhel-8.2
  naughty/rhel-8/838-libvirtd-dumps-core
Labels: bot

#2442 naughty: Close 1680: debian-testing: ifupdown scripts interfere with NetworkManager
  naughty/debian-stable/1680-ifupdown-interferes-with-bonding
  naughty/debian-testing/1680-ifupdown-interferes-with-bonding
Labels: bot

#2349 testmap: Test cockpit-machines on fedora-35
  lib/testmap.py
Labels: bot

#2438 testmap: promote rhel-8-6 for cockpit from _manual
  lib/testmap.py
Labels: no-test

#2440 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#2449 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2448 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2450 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2452 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2454 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2453 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2457 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2459 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2458 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2461 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test
