Repository cockpit-project/bots, pull requests merged in 2021-06, with the labels that each got.

#2070 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2069 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2068 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2072 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2074 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2077 images: Use only first link when looking for a bootstrap image
  images/scripts/fedora-33.bootstrap
  images/scripts/fedora-34.bootstrap
Labels: bot

#2080 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2083 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2078 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2100 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2098 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2102 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2101 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2084 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2105 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2099 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2117 naughty: Close 1492: Fedora CoreOS regression: avc: denied { read } for name="stub-resolv.conf"
  naughty/fedora-coreos/1492-selinux-stub-resolv.conf
Labels: bot

#2114 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2120 testmap: add new _manual triggers for cockpit
  lib/testmap.py
Labels: no-test

#2125 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2129 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2128 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2126 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2127 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2115 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2132 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2135 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2137 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2136 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2139 naughty: Close 2032: Fedora CoreOS: avc: denied { watch } for comm="agetty" path="/run/agetty.reload"
  naughty/fedora-coreos/2032-selinux-agetty.reload
Labels: bot

#2140 naughty: Close 1957: udisks2: formatting vfat times out
  naughty/ubuntu-stable/1957-udisks-vfat-format
Labels: bot

#2143 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2149 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2148 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2146 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2147 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2151 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2155 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2157 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2159 testmap: run firefox scenario on fedora-34 image
  lib/testmap.py
Labels: no-test
