Repository cockpit-project/bots, pull requests merged in 2021-04, with the labels that each got.

#1828 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1876 naughty: Close 1436: podman rootless mode doesn't work
  naughty/rhel-8/1436-podman-rootless-smootless
Labels: bot

#1874 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1884 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1882 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1885 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#1880 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1883 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1892 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#1891 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1890 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1889 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1899 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1897 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1906 naughty: Close 1735: fedora-34: joining AD domain fails: Couldn't join realm: Enabling SSSD in nsswitch.conf and PAM failed
  naughty/fedora-34/1735-realm-ad-authconfig
  naughty/fedora-34/1735-realm-ad-authconfig-2
  naughty/rhel-9/1735-realm-ad-authconfig
  naughty/rhel-9/1735-realm-ad-authconfig-2
Labels: bot

#1904 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1920 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1919 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1918 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1917 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1916 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1915 naughty: adjust cryptsetup systemd unmount fs naughty
  naughty/fedora-33/1739-cryptsetup-systemd-umount-fs-2
  naughty/fedora-34/1739-cryptsetup-systemd-umount-fs-2
Labels: blocked, no-test

#1922 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#1926 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1929 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1931 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1933 naughty: Close 1453: fsadm crashes with "unbound variable"
  naughty/rhel-7/1453-fsadm-unbound-variable
  naughty/rhel-8/1453-fsadm-unbound-variable
Labels: bot

#1921 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#1923 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1930 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1937 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#1936 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1943 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1946 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1945 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1953 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1951 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1949 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1948 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#1950 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1959 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1960 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#1965 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1963 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#1964 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1967 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1966 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1968 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1972 naughty: Close 1663: [RHEL-8] boot vm from pxe fails
  naughty/rhel-8/1663-boot-vm-pxe-fails
Labels: bot

#1971 naughty: Close 1784: fedora-34: reportd crashes in reportd_task_start
  naughty/fedora-34/1784-reportd-crash-task_start
Labels: bot

#1969 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test
