Repository cockpit-project/bots, pull requests merged in 2021-07, with the labels that each got.

#2161 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2166 naughty: Close 1993: ncat segfault when making connection do unix domain socket
  naughty/rhel-9/1993-ncat-segfault
  naughty/rhel-9/1993-ncat-segfault-2
Labels: bot

#2176 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2172 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2174 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2175 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2173 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2160 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2184 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2183 images: Build samba-domain container locally
  .github/workflows/daily.yml
  images/scripts/services.setup
  images/services
  sync-quay
Labels: bot

#2190 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2189 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2188 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2196 naughty: Close 1785: fedora-34: reportd crashes
  naughty/fedora-34/1785-reportd-crash
  naughty/fedora-34/1785-reportd-crash-2
Labels: bot

#2201 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2199 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2198 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2200 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2203 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2204 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2205 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2206 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2207 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2208 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#2212 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2211 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, needswork, no-test

#2216 naughty: Close 1236: kvdo module broken on CentOS 8
  naughty/rhel-8/1236-no-kvdo
Labels: bot

#2217 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2224 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2223 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2222 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2225 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2210 Image refresh for fedora-34
  images/fedora-34
Labels: bot, needswork, no-test

#2227 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2229 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2228 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#2232 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2241 naughty: Close 798: Libvirtd dumps core when stopped too quickly
  naughty/fedora-33/798-libvirtd-coredump
  naughty/rhel-8/798-libvirtd-coredump
Labels: bot

#2240 naughty: Close 1893: RHEL 9: podman: configured runtime does not support checkpoint/restore
  naughty/rhel-9/1893-podman-checkpoint-restore
Labels: bot

#2239 naughty: Close 2031: fedora-coreos: avc: denied { write } for comm="systemd-hostnam" name="systemd" dev="tmpfs"
  naughty/fedora-coreos/2031-selinux-systemd-hostnam
Labels: bot

#2237 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#2242 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#2246 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#2245 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#2202 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#2250 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#2251 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#2252 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#2247 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#2254 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#2257 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#2260 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#2261 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test
