Repository cockpit-project/bots, pull requests merged in 2021-03, with the labels that each got.

#1726 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1730 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1731 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1737 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1736 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1738 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1742 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1751 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1758 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1757 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1760 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1762 naughty: Close 1647: podman regression in rawhide: `build` fails on `bpf create`
  naughty/fedora-33/1647-podman-bpf
Labels: bot

#1763 naughty: Close 1635: podman regression in Debian testing: could not get either XDG_CONFIG_HOME or HOME: Internal Server Error
  naughty/debian-testing/1635-api-commit-HOME
Labels: bot

#1764 naughty: Close 928: Denied NetworkManager write to /var/tmp/dracut.*/systemd-cat while generating initrd image
  naughty/rhel-8/928-selinux-nm-system-cat
Labels: bot

#1753 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1772 lib: split stores into a text file
  lib/stores
  lib/stores.py
Labels: bot

#1775 image-refresh: don't run image-diff on all images
  image-refresh
Labels: bot

#1779 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1778 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1776 Image refresh for fedora-33
  images/fedora-33
Labels: bot, no-test

#1777 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#1789 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1788 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1793 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1791 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#1792 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1752 Image refresh for fedora-32
  images/fedora-32
Labels: bot, no-test

#1803 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1802 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1807 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1811 naughty: Close 1662: SELinux complaining when osbuild is removing the machine-id for an image that seems to be in tmp
  naughty/rhel-8/1662-selinux-osbuild-composer-machine-id
Labels: bot

#1808 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#1809 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1815 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1819 testmap: Create a new entry for cockpit-machines repository
  lib/testmap.py
Labels: no-test

#1821 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1826 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1827 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1839 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#1838 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#1837 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1836 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#1822 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1841 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#1845 naughty: Close 1657: [RHEL-8] avc: denied { node_bind } comm="rhsmcertd-worke"
  naughty/rhel-8/1657-selinux-node_bind-rhsmcertd
Labels: bot

#1844 naughty: Close 1688: fedora-34: SELinux is preventing abrt-dump-journ from 'watch' accesses on the directory /run/log/journal
  naughty/fedora-34/1688-selinux-abrt
Labels: bot

#1843 naughty: Close 1691: RHEL 8.4 regression: Job for pmlogger.service failed because the service did not take the steps required by its unit configuration
  naughty/rhel-8/1691-pmlogger-start-failure
Labels: bot

#1852 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#1855 Image refresh for rhel-8-3
  images/rhel-8-3
Labels: bot, no-test

#1854 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#1858 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#1869 Image refresh for rhel-atomic
  images/rhel-atomic
Labels: bot, no-test

#1867 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#1868 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test
