Repository cockpit-project/bots, pull requests merged in 2022-08, with the labels that each got.

#3672 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test, blocked

#3684 Image refresh for arch
  images/arch
Labels: bot, no-test

#3686 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3687 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3688 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3689 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3690 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3692 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3691 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3693 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3669 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3694 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3698 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3695 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3697 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3702 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3701 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3716 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3715 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3714 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3713 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3712 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3711 Image refresh for arch
  images/arch
Labels: bot, no-test

#3718 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3719 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3720 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3721 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3723 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3732 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3731 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3730 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3729 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3727 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3726 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3725 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3733 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3739 Image refresh for arch
  images/arch
Labels: bot, no-test

#3736 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3749 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3750 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3748 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3751 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3755 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3740 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3766 images: add fedora-37
  images/fedora-37
  images/scripts/fedora-37.bootstrap
  images/scripts/fedora-37.setup
  lib/testmap.py
Labels: bot

#3757 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3761 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3758 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3756 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3768 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3772 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3770 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3777 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3769 Image refresh for arch
  images/arch
Labels: bot, no-test

#3778 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3776 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3775 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3779 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3782 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3781 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3789 image-create: Allow slow fedora-rawhide boots
  image-create
Labels: bot

#3788 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3743 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3759 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3792 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3793 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3790 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3791 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test, blocked

#3771 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3762 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3802 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test
