Repository cockpit-project/bots, pull requests merged in 2022-05, with the labels that each got.

#3318 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3320 Image refresh for arch
  images/arch
Labels: bot, no-test

#3308 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3310 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3305 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3304 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3309 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3325 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3326 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3328 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3329 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3327 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3332 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3301 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: needswork, bot, no-test

#3306 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3335 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3345 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3343 naughty: Close 2898: useradd causes avc: denied { execute } for pid=57884 comm="chpasswd|chage" name="sss_cache"
  naughty/fedora-35/2898-selinux-chage-sss_cache
  naughty/fedora-35/2898-selinux-chpasswd-sss_cache
  naughty/fedora-36/2898-selinux-chage-sss_cache
  naughty/fedora-36/2898-selinux-chpasswd-sss_cache
  naughty/fedora-coreos/2898-selinux-chage-sss_cache
  naughty/fedora-coreos/2898-selinux-chpasswd-sss_cache
  naughty/rhel-8/2898-selinux-chpasswd-sss_cache
  naughty/rhel-9/2898-selinux-chpasswd-sss_cache
Labels: bot

#3342 naughty: Close 3121: modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-372.2.1.el8.x86_64
  naughty/rhel-8/3121-no-kvdo
Labels: bot

#3341 naughty: Close 3200: Starting VM with UEFI firmware fails with swtpm
  naughty/ubuntu-2204/3200-libvirt-uefi-swtpm
Labels: bot

#3338 naughty: Close 3200: Starting VM with UEFI firmware fails with swtpm
  naughty/ubuntu-2204/3200-libvirt-uefi-swtpm
Labels: bot

#3339 naughty: Close 3121: modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-372.2.1.el8.x86_64
  naughty/ubuntu-2204/3200-libvirt-uefi-swtpm
Labels: bot

#3353 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3352 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3350 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3349 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3348 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3347 Image refresh for arch
  images/arch
Labels: bot, no-test

#3358 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3351 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3357 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3366 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3316 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test, blocked

#3369 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3370 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3372 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3374 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3384 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3381 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3382 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3383 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3380 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3393 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3395 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3394 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3392 Image refresh for arch
  images/arch
Labels: bot, no-test

#3397 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3407 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3406 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3411 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3416 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3415 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3414 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3413 setup-deploy-keys: move website to its own environment
  setup-deploy-keys
Labels: blocked

#3421 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3396 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: needswork, bot, no-test

#3428 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3427 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3426 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3425 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3429 image-download: Avoid walrus operator (quick alternative to #3430)
  image-download
Labels: blocked

#3439 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3440 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3438 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3434 Image refresh for arch
  images/arch
Labels: bot, no-test

#3442 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3441 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3435 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3447 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3446 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3437 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: no-test
