Repository cockpit-project/bots, pull requests merged in 2022-07, with the labels that each got.

#3576 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3578 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3577 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3579 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3581 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3583 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3584 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3582 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3588 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3589 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3587 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3586 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3594 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3597 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3595 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3593 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3600 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3601 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3602 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3552 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3603 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3609 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3607 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3605 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3610 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3612 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3613 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3615 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3614 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3624 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3623 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3622 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3621 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3620 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3626 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3625 Image refresh for arch
  images/arch
Labels: bot, no-test

#3632 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3631 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3634 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3637 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3642 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3655 Image refresh for arch
  images/arch
Labels: bot, no-test

#3656 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3648 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3649 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3650 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3647 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3645 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3646 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3638 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3651 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3661 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3660 task: Switch over main AMQP server to AWS
  task/distributed_queue.py
Labels: blocked

#3606 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test, blocked

#3667 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test
