Repository cockpit-project/bots, pull requests merged in 2022-04, with the labels that each got.

#3176 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3175 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3178 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3177 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3180 testmap: tweak OSes for sub-man-cockpit
  lib/testmap.py
Labels: needswork

#3186 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#3185 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3184 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3188 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3190 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3174 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3193 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3196 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3197 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3203 Image refresh for arch
  images/arch
Labels: bot, no-test

#3205 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3214 naughty: Close 2998: selinux: systemd-sysctl was denied reading suid_dumpable, protected_hardlinks, and protected_symlinks
  naughty/rhel-9/2998-selinux-systemd-sysctl
Labels: bot

#3215 naughty: Close 2997: SELinux is preventing systemd-coredum from 'sys_admin' accesses to coredumps on rhel-9-0
  naughty/rhel-9/2997-selinux-systemd-coredum
Labels: bot

#3216 naughty: Close 2988: abrt reportd can't access coredumps due to SELinux
  naughty/fedora-36/2988-selinux-coredumpctl
  naughty/fedora-36/2988-testabrt-abrtreport
  naughty/fedora-36/2988-testabrt-abrtsegv
  naughty/fedora-36/2988-testabrt-reportcancel
Labels: bot

#3204 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3221 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3222 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3223 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3224 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3225 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#3229 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3230 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3228 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3235 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3234 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3233 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3236 task: stop creating detached branches
  task/__init__.py
Labels: bot

#3238 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3239 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3241 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3240 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3244 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3243 Image refresh for arch
  images/arch
Labels: bot, no-test

#3245 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3246 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3250 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#3249 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3254 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3255 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3262 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3264 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3260 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3263 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3261 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3292 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3291 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3289 Image refresh for arch
  images/arch
Labels: bot, no-test

#3285 naughty: Close 3146: ubuntu 22.04: pam_faillock does not actually deny login after given number of failures
  naughty/ubuntu-2204/3146-pam_faillock-no-lock
Labels: bot

#3287 naughty: Close 2919: avc: denied { module_request } comm="ksmtuned"
  naughty/rhel-8/2919-selinux-ksmtuned
Labels: bot

#3284 naughty: Close 3163: targetcli delete fails with: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'
  naughty/fedora-37/3163-targetcli-delete
  naughty/fedora-37/3163-targetcli-delete-followup
Labels: bot

#3302 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test
