Repository cockpit-project/bots, pull requests merged in 2022-11, with the labels that each got.

#4011 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4015 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4005 [no-test] Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4017 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4018 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4016 Image refresh for fedora-37
  images/fedora-37
Labels: needswork, bot, no-test

#4019 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4024 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4020 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#4023 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4021 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4022 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4025 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#4028 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4029 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#4027 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4035 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4034 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#4036 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4037 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4026 Image refresh for arch
  images/arch
Labels: bot, no-test

#4012 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4047 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#4046 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4045 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3966 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#4044 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#4041 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4056 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4055 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4054 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4053 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4060 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4062 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4058 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4063 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#4066 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4071 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4070 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4072 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4065 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#4085 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4084 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4081 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4080 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4079 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3957 testmap: update cockpit composer testing
  lib/testmap.py
Labels: needs-rebase, blocked

#4088 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4087 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4078 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4076 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#4082 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4090 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4091 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#4075 task: Report task status/logs directly to GitHub/S3, drop sink
  HACKING.md
  image-refresh
  lib/network.py
  task/__init__.py
  task/sink.py
  task/test-task
Labels: bot

#4093 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#4095 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4101 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#4102 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4104 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4105 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4109 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4107 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4106 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4108 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4114 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#4115 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4116 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#4112 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4099 Image refresh for arch
  images/arch
Labels: needswork, bot, no-test

#4100 Image refresh for fedora-36
  images/fedora-36
Labels: needswork, bot, no-test
