Repository cockpit-project/bots, pull requests merged in 2022-03, with the labels that each got.

#3013 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3017 Image refresh for arch
  images/arch
Labels: bot, no-test

#3014 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3024 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3025 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3029 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#3030 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3023 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3031 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3032 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#3037 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3036 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3035 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3041 naughty: Close 2359: avc: denied { watch watch_reads } comm="systemd-tty-ask" path="/dev/tty1
  naughty/fedora-34/2359-selinux-tty-askpass-watch_reads
  naughty/fedora-35/2359-selinux-tty-askpass-watch_reads
  naughty/rhel-9/2359-selinux-tty-askpass-watch_reads
Labels: bot

#3038 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3047 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3054 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3055 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3061 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3063 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3062 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#3070 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3072 Image refresh for ubuntu-2004
  images/ubuntu-2004
Labels: bot, no-test

#3071 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3077 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3076 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3075 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3074 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3080 naughty: Close 2799: SELinux is preventing systemd-user-ru from 'unlink' accesses on the lnk_file user
  naughty/fedora-34/2799-selinux-unlink-systemd-user-ru
  naughty/rhel-9/2799-selinux-unlink-systemd-user-ru
Labels: bot

#3079 naughty: Close 2809: Unable to use ping as a regular user
  naughty/rhel-8/2809-broken-ping
Labels: bot

#3081 naughty: Close 2775: "virt-xml --remove-device --network" fails with QEMU 6.2 update
  naughty/arch/2775-virtxml-remove-net
  naughty/debian-testing/2775-virtxml-remove-net
  naughty/fedora-36/2775-virtxml-remove-net
  naughty/rhel-8/2775-virtxml-remove-net
  naughty/rhel-9/2775-virtxml-remove-net
Labels: bot

#3083 naughty: Close 2464: Cannot get logs with --follow
  naughty/rhel-8/2464-logs-with-follow
  naughty/rhel-9/2464-logs-with-follow
Labels: bot

#3084 naughty: Close 1784: fedora: reportd crashes in reportd_task_start
  naughty/fedora-35/1784-reportd-crash-task_start
Labels: bot

#3085 naughty: Close 773: rhel-7-9: rhsmd fails with 'ImportError: No module named psutil'
  naughty/rhel-7/773-rhsmd-import-error
  naughty/rhel-7/773-rhsmd-import-error-1
  naughty/rhel-7/773-rhsmd-import-error-2
  naughty/rhel-7/773-rhsmd-import-error-3
Labels: bot

#3103 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3027 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3109 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3107 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3110 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3108 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3116 Image refresh for fedora-34
  images/fedora-34
Labels: bot, no-test

#3117 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3120 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3125 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3124 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3128 naughty: Close 2840: No memory reserved when crashkernel=auto
  naughty/rhel-9/2840-kdump-no-memory
Labels: bot

#3127 naughty: Close 2877: udev can't create /dev/stratis/poolname/fsname links any more: vc: denied { associate } for comm="systemd-udevd" name="stratis"
  naughty/fedora-35/2877-selinux-stratis-devlinks
  naughty/fedora-35/2877-selinux-stratis-devlinks-msg
  naughty/rhel-8/2877-selinux-stratis-devlinks
  naughty/rhel-8/2877-selinux-stratis-devlinks-msg
Labels: bot

#3130 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3141 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3143 WIP: 2-cockpit-7: [no-test] images: Only run podman in debian.setup when it is available
  images/scripts/debian.setup
Labels: bot

#3149 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3150 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#3151 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3142 Image refresh for fedora-testing
  images/fedora-testing
Labels: needswork, bot, no-test

#3161 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3158 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3154 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3159 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3165 image-upload: Retry upload up to three times
  image-upload
Labels: bot

#3160 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3167 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#3170 naughty: Close 2626: Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
  naughty/rhel-8/2626-insights-client-import-error
Labels: bot

#3171 naughty: Close 2567: polkit_system_bus_name_get_creds_sync(): polkitd killed by SIGTRAP
  naughty/debian-testing/2567-polkit-crash-system_bus_name_get_creds_sync
  naughty/fedora-35/2567-polkit-crash-system_bus_name_get_creds_sync
  naughty/rhel-9/2567-polkit-crash-system_bus_name_get_creds_sync
  naughty/ubuntu-stable/2567-polkit-crash-system_bus_name_get_creds_sync
Labels: bot
