Repository cockpit-project/bots, pull requests merged in 2022-06, with the labels that each got.

#3461 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3459 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3467 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3471 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3463 images: Use last cloud image for bootstrapping, not first
  images/scripts/arch.bootstrap
  images/scripts/fedora-35.bootstrap
  images/scripts/fedora-36.bootstrap
  images/scripts/fedora-rawhide.bootstrap
Labels: bot

#3470 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3472 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3477 Image refresh for arch
  images/arch
Labels: bot, no-test

#3478 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3480 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3482 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3485 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3483 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3484 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3479 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3486 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3489 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3490 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3492 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3493 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3495 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3494 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3491 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3498 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3497 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3502 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#3506 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3507 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3508 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3510 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3500 Image refresh for arch
  images/arch
Labels: needswork, bot, no-test

#3514 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3518 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#3519 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3515 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3516 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3523 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3488 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3530 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3540 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3538 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#3536 Image refresh for arch
  images/arch
Labels: bot, no-test

#3542 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3541 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3537 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3549 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#3496 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test, blocked

#3550 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#3551 Image refresh for fedora-35
  images/fedora-35
Labels: bot, no-test

#3553 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#3554 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#3555 Image refresh for rhel-8-5
  images/rhel-8-5
Labels: bot, no-test

#3556 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#3564 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#3563 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#3567 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#3566 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#3569 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#3573 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#3572 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#3571 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#3568 Image refresh for arch
  images/arch
Labels: bot, no-test

#3570 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test
