Repository cockpit-project/bots, pull requests merged in 2023-02, with the labels that each got.

#4344 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4345 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#4350 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4349 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4360 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4359 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4358 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4356 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4364 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4363 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4362 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#4361 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4370 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4369 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4374 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4372 Image refresh for arch
  images/arch
Labels: bot, no-test

#4373 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4376 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#4351 images: Add needed packages for Cockpit tests
  images/rhel4edge
  images/scripts/ostree.setup
  images/scripts/rhel4edge.bootstrap
Labels: bot

#4379 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4378 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4383 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4382 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4352 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#4377 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#4385 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#4389 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4388 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4387 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4386 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4396 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4395 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4393 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4401 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4399 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4402 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#4400 Image refresh for debian-testing
  images/debian-testing
Labels: needswork, bot, no-test

#4407 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4406 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#4405 Image refresh for arch
  images/arch
Labels: bot, no-test

#4417 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#4420 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4421 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4422 Image refresh for fedora-36
  images/fedora-36
Labels: bot, no-test

#4424 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4425 Image refresh for services
  images/services
Labels: bot, no-test

#4419 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4426 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4430 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4429 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#4427 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#4423 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#4435 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#4433 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#4394 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: needswork, bot, no-test

#4442 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#4441 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4440 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#4439 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#4445 Refresh fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#4434 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#4431 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#4454 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#4453 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#4452 Image refresh for rhel-9-1
  images/rhel-9-1
Labels: bot, no-test

#4448 Image refresh for rhel-8-7
  images/rhel-8-7
Labels: bot, no-test

#4455 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#4457 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#4463 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#4467 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#4466 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test
