Repository cockpit-project/bots, pull requests merged in 2023-09, with the labels that each got.

#5197 Image refresh for fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload-b9cab41ceb8b52f530d090fa62aa34e8e00f093c078f388244eb9bd9cec4d371.tar.gz
  images/fedora-rawhide-anaconda-payload-da9a1fa220015d8c75e76e5fb4340f1b9dd47982706340e334c7f81f63ce8531.tar.gz
Labels: bot, no-test

#5196 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#5195 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#5194 Image refresh for arch
  images/arch
Labels: bot, no-test

#5160 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#5165 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#5164 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#5189 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#5163 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#5201 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#5203 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#5210 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5209 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#5208 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5207 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#5213 Image refresh for fedora-39-boot
  images/fedora-39-boot
Labels: bot, no-test

#5169 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5220 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#5217 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5221 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#5218 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#5215 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#5216 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#5219 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#5185 Capture VM's console if VM hangs on boot or poweroff
  image-create
  image-refresh
  machine/machine_core/machine.py
  machine/machine_core/machine_virtual.py
  machine/machine_core/ssh_connection.py
Labels: bot

#5225 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5224 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#5236 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#5235 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#5234 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#5237 Image refresh for fedora-testing
  images/fedora-testing
Labels: bot, no-test

#5238 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#5233 Image refresh for arch
  images/arch
Labels: bot, no-test

#5242 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#5251 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5250 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#5249 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5248 Image refresh for fedora-39-boot
  images/fedora-39-boot
Labels: bot, no-test

#5255 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5262 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#5258 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#5259 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#5188 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5261 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#5266 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5265 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#5267 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#5269 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#5268 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#5270 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#5271 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#5260 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test, blocked

#5272 Image refresh for arch
  images/arch
Labels: bot, no-test

#5277 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#5278 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5279 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5280 Image refresh for Fedora 38
  images/fedora-38
Labels: bot, no-test

#5282 Image refresh for fedora-39-boot
  images/fedora-39-boot
Labels: bot, no-test

#5283 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5284 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5297 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5296 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#5294 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5293 Image refresh for centos-7
  images/centos-7
Labels: bot, no-test

#5298 Image refresh for fedora-37
  images/fedora-37
Labels: bot, no-test

#5299 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#5302 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#5301 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#5303 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#5300 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#5305 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#5307 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#5306 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#5310 images: Add rhel-8-10
  image-trigger
  images/scripts/rhel-8-10.bootstrap
  images/scripts/rhel-8-10.setup
  images/scripts/rhel.setup
  lib/testmap.py
  naughty/rhel-8-10
Labels: bot

#5311 ruff: Enable UP032 f-string rule
  github-info
  image-create
  image-customize
  image-download
  image-refresh
  image-trigger
  inspect-queue
  issue-scan
  machine/machine_core/machine.py
  machine/machine_core/machine_virtual.py
  machine/machine_core/ssh_connection.py
  naughty-prune
  npm-update
  po-refresh
  push-rewrite
  pyproject.toml
  store-tests
  task/__init__.py
  task/github.py
  task/test-github
  test-failure-policy
  tests-invoke
  tests-policy
  tests-scan
  tests-trigger
  vm-run
Labels: bot

#5312 Image refresh for arch
  images/arch
Labels: bot, no-test

#5318 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5317 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5316 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#5321 Image refresh for fedora-39-boot
  images/fedora-39-boot
Labels: bot, no-test

#5324 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test
