Repository cockpit-project/bots, pull requests merged in 2024-05, with the labels that each got.

#6324 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#6323 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#6325 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#6326 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#6327 images: centos9 bootc is now xfs
  images/scripts/lib/bootc.bootstrap
Labels: bot

#6328 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#6329 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#6331 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#6330 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#6335 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#6336 Image refresh for arch
  images/arch
Labels: bot, no-test

#6337 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#6345 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#6343 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#6342 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#6355 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#6354 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#6353 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#6361 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#6360 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#6359 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#6358 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#6352 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#6366 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#6364 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#6365 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#6371 Image refresh for arch
  images/arch
Labels: bot, no-test

#6370 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#6381 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#6383 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#6382 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#6386 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#6392 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#6391 Image refresh for fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload
Labels: bot, no-test

#6387 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#6388 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#6390 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#6389 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#6394 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#6399 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#6398 Image refresh for rhel-9-0
  images/rhel-9-0
Labels: bot, no-test

#6397 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#6396 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#6395 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#6407 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#6406 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#6405 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#6404 Image refresh for arch
  images/arch
Labels: bot, no-test

#6410 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#6421 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#6420 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test, blocked

#6423 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#6424 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#6428 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#6429 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#6431 naughty: drop #6374 on ubuntu-2204
  naughty/ubuntu-2204/6374-ubuntu-advantage-etc-os-release
Labels: bot

#6425 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#6393 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#6433 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#6436 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#6435 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#6440 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#6439 Image refresh for arch
  images/arch
Labels: bot, no-test

#6445 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#6444 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#6449 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#6448 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test
