Repository cockpit-project/bots, pull requests merged in 2024-02, with the labels that each got.

#5857 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5856 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#5855 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5854 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#5853 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#5859 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5858 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5862 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#5863 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#5864 Image refresh for services
  images/services
Labels: bot, no-test

#5868 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5879 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#5821 Image refresh for fedora-eln
  images/fedora-eln
Labels: bot

#5878 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#5883 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#5882 use proper ID for downloading ISO artifact (use InstallerID)
  images/rhel4edge
  images/scripts/rhel4edge.bootstrap
Labels: bot, no-test

#5890 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5889 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#5888 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5894 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5895 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#5898 Image refresh for fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload
Labels: bot, no-test

#5886 Quickie rawhide refresh
  images/fedora-rawhide
Labels: bot, no-test

#5899 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5902 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#5903 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#5914 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5909 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#5908 Image refresh for arch
  images/arch
Labels: bot, no-test

#5912 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#5910 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5920 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#5924 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5922 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5925 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5928 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#5936 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5934 Image refresh for fedora-38
  images/fedora-38
Labels: bot, no-test

#5947 Image refresh for arch
  images/arch
Labels: bot, no-test

#5950 Image refresh for rhel4edge
  images/rhel4edge
Labels: bot, no-test

#5949 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#5948 Image refresh for centos-8-stream
  images/centos-8-stream
Labels: bot, no-test

#5931 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#5968 Image refresh for rhel-8-6
  images/rhel-8-6
Labels: bot, no-test

#5967 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#5970 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#5969 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#5972 Image refresh for rhel-9-3
  images/rhel-9-3
Labels: bot, no-test

#5971 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#5973 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#5974 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#5976 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#5975 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#5983 Image refresh for rhel-8-9
  images/rhel-8-9
Labels: bot, no-test

#5982 Image refresh for rhel-7-9
  images/rhel-7-9
Labels: bot, no-test

#5984 testmap: Drop fedora-38 from our projects
  lib/testmap.py
Labels: blocked

#5988 Image refresh for rhel-8-4
  images/rhel-8-4
Labels: bot, no-test

#5987 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#5991 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#5992 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test
