Repository cockpit-project/bots, pull requests merged in 2024-12, with the labels that each got.

#7165 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7167 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7174 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7173 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7172 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7171 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#6182 README.md: Document how to create a new CI image
  README.md
Labels: no-test

#7176 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7178 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#7177 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7179 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7181 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7180 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7183 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7182 testmap: Add 'efi' firmware test scenario for anaconda-webui
  lib/testmap.py
Labels: blocked

#7186 Image refresh for arch
  images/arch
Labels: bot, no-test

#7192 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7191 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7190 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7188 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#7187 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7193 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7189 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7201 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7200 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#7199 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7208 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7206 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#7205 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7204 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7203 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7202 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7207 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7212 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7213 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7215 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7216 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7219 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7217 Image refresh for arch
  images/arch
Labels: bot, no-test

#7218 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7222 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7221 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#7223 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7220 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7226 images: Update to new cockpit CI CA certificate
  images/files/ca.pem
Labels: blocked

#7227 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7229 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7231 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7232 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7230 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7228 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7235 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7234 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7236 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7239 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7237 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7240 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7243 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7242 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7241 Image refresh for arch
  images/arch
Labels: bot, no-test

#7248 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7247 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7245 Image refresh for fedora-39
  images/fedora-39
Labels: bot, no-test

#7256 Image refresh for services
  images/services
Labels: bot, no-test

#7255 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7254 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7253 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7252 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7250 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7249 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7251 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7258 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7259 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7261 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7262 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7263 Image refresh for fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload
Labels: bot, no-test

#7267 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7265 Image refresh for arch
  images/arch
Labels: bot, no-test

#7266 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test
