Repository cockpit-project/bots, pull requests merged in 2025-04, with the labels that each got.

#7605 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7609 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7606 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7608 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7610 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7617 Image refresh for rhel-10-1
  images/rhel-10-1
Labels: bot, no-test

#7616 Image refresh for rhel-9-7
  images/rhel-9-7
Labels: bot, no-test

#7615 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7614 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7619 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7618 Image refresh for services
  images/services
Labels: bot, no-test

#7620 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7621 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7625 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7634 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7633 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7635 Image refresh for fedora-42-boot
  images/fedora-42-boot
Labels: bot, no-test

#7638 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7642 Image refresh for rhel-10-1
  images/rhel-10-1
Labels: bot, no-test

#7641 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7639 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7643 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7644 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7640 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: needswork, bot, no-test, blocked

#7650 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#7651 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7654 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7653 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#7652 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7658 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7657 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7659 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7666 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7667 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7668 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7669 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7671 Image refresh for arch
  images/arch
Labels: bot, no-test

#7674 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7676 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7677 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7682 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7683 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7684 Image refresh for fedora-42
  images/fedora-42
Labels: bot, no-test

#7645 Image refresh for fedora-rawhide-anaconda-payload
  images/fedora-rawhide-anaconda-payload
Labels: bot, no-test

#7690 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7691 Image refresh for rhel-10-1
  images/rhel-10-1
Labels: bot, no-test

#7696 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7698 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7697 Image refresh for arch
  images/arch
Labels: bot, no-test

#7673 Image refresh for rhel-9-7
  images/rhel-9-7
Labels: bot, no-test, blocked

#7702 image-create: Remove old image before installing new one
  image-create
Labels: bot

#7706 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7636 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test, blocked

#7704 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7705 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7709 Fedora 41 refresh
  images/fedora-41
Labels: bot, no-test
