Repository cockpit-project/bots, pull requests merged in 2025-06, with the labels that each got.

#7836 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7833 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7850 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7848 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7846 Image refresh for arch
  images/arch
Labels: bot, no-test

#7843 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7842 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7856 Image refresh for rhel-9-7
  images/rhel-9-7
Labels: bot, no-test

#7854 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7860 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7859 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7858 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7862 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7865 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7863 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test, blocked

#7869 Image refresh for arch
  images/arch
Labels: bot, no-test

#7873 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7879 Image refresh for rhel-9-7
  images/rhel-9-7
Labels: bot, no-test

#7878 Image refresh for fedora-42
  images/fedora-42
Labels: bot, no-test

#7882 images: only rhel-10-1 and higher has stratisd-tools
  images/scripts/rhel.setup
Labels: bot

#7888 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7886 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7898 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7901 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7902 Image refresh for debian-testing
  images/debian-testing
Labels: bot, no-test

#7906 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7904 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7903 Image refresh for arch
  images/arch
Labels: bot, no-test

#7908 Image refresh for rhel-9-7
  images/rhel-9-7
Labels: bot, no-test

#7905 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7877 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7912 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7916 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7910 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7918 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7924 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7931 Image refresh for arch
  images/arch
Labels: bot, no-test

#7933 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7932 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test
