Repository cockpit-project/bots, pull requests merged in 2025-02, with the labels that each got.

#7381 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7385 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7389 Image refresh for rhel-8-8
  images/rhel-8-8
Labels: bot, no-test

#7388 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7386 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7393 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7390 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7394 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7391 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7392 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7395 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7402 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7401 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7408 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7412 Image refresh for opensuse-tumbleweed
  images/opensuse-tumbleweed
Labels: bot, no-test

#7411 Image refresh for fedora-rawhide-live-boot
  images/fedora-rawhide-live-boot
Labels: bot, no-test

#7403 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7400 Image refresh for fedora-rawhide-boot
  images/fedora-rawhide-boot
Labels: bot, no-test

#7418 Image refresh for rhel-9-2
  images/rhel-9-2
Labels: bot, no-test

#7417 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7430 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7435 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7438 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7434 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7436 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7439 Image refresh for fedora-rawhide
  images/fedora-rawhide
Labels: bot, no-test

#7440 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7444 Image refresh for rhel-9-6
  images/rhel-9-6
Labels: bot, no-test

#7443 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7445 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7447 Image refresh for arch
  images/arch
Labels: bot, no-test

#7452 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test

#7453 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7457 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test

#7460 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7456 Image refresh for debian-stable
  images/debian-stable
Labels: bot, no-test

#7459 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7464 Image refresh for rhel-9-5
  images/rhel-9-5
Labels: bot, no-test

#7463 Image refresh for rhel-9-4
  images/rhel-9-4
Labels: bot, no-test

#7461 Image refresh for ubuntu-2204
  images/ubuntu-2204
Labels: bot, no-test

#7462 Image refresh for rhel-8-10
  images/rhel-8-10
Labels: bot, no-test

#7466 Image refresh for ubuntu-2404
  images/ubuntu-2404
Labels: bot, no-test

#7467 Image refresh for centos-9-bootc
  images/centos-9-bootc
Labels: bot, no-test

#7470 Image refresh for centos-9-stream
  images/centos-9-stream
Labels: bot, no-test

#7455 Image refresh for fedora-42
  images/fedora-42
Labels: bot, no-test

#7476 Image refresh for fedora-40
  images/fedora-40
Labels: bot, no-test

#7475 Image refresh for arch
  images/arch
Labels: bot, no-test

#7477 Image refresh for rhel-10-0
  images/rhel-10-0
Labels: bot, no-test, blocked

#7480 lib: testmap: add two new anaconda test scenarios
  lib/testmap.py
Labels: blocked

#7482 Image refresh for centos-10
  images/centos-10
Labels: bot, no-test

#7486 Image refresh for ubuntu-stable
  images/ubuntu-stable
Labels: bot, no-test

#7485 Image refresh for fedora-coreos
  images/fedora-coreos
Labels: bot, no-test

#7484 Image refresh for fedora-41
  images/fedora-41
Labels: bot, no-test
